 const  actionTypes={
   LOGIN_LOADING_ACTION:"LOGIN_LOADING_ACTION",
   LOGIN_RESPONSE_ACTION:"LOGIN_RESPONSE_ACTION",
   LOGIN_ERROR_ACTION:"LOGIN_ERROR_ACTION",
   DECODE_TOKEN:"DECODE_TOKEN",
   DECODE_TOKEN_ERROR:"DECODE_TOKEN_ERROR",
   CREATE_USER_LOADING_ACTION:"CREATE_USER_LOADING_ACTION",
   CREATE_USER_RESPONSE_ACTION:"CREATE_USER_RESPONSE_ACTION",
   CREATE_USER_ERROR_ACTION:"CREATE_USER_ERROR_ACTION",
   CREATE_USER_REFRESH_ACTION:"CREATE_USER_REFRESH_ACTION",
   GET_ALL_USERS_LOADING_ACTION:"GET_ALL_USERs_LOADING_ACTION",
   GET_ALL_USERS_RESPONSE_ACTION:"GET_ALL_USERs_LOADING_ACTION",
   GET_ALL_USERS_ERROR_ACTION:"GET_ALL_USERs_LOADING_ACTION",
   GET_ALL_STUDENTS_LOADING_ACTION:"GET_ALL_STUDENTS_LOADING_ACTION",
   GET_ALL_STUDENTS_RESPONSE_ACTION:"GET_ALL_STUDENTS_RESPONSE_ACTION",
   GET_ALL_STUDENTS_ERROR_ACTION:"GET_ALL_STUDENTS_ERROR_ACTION",
   GET_ALL_LEVELS_LOADING_ACTION:"GET_ALL_LEVELS_LOADING_ACTION",
   GET_ALL_LEVELS_RESPONSE_ACTION:"GET_ALL_LEVELS_RESPONSE_ACTION",
   GET_ALL_LEVELS_ERROR_ACTION:"GET_ALL_LEVELS_ERROR_ACTION",
   LEVEL_CHANGE:"LEVEL_CHANGE"
}

export default actionTypes;